export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const GET_FILM = 'GET_FILM'
export const GET_FILM_SUCCESS = 'GET_FILM_SUCCESS'
export const GET_FILM_ERROR = 'GET_FILM_ERROR'


